plugins {
    id 'java-library'
}

stonecutter {
    properties.tags(('versions:' + current.version).toString())
}

def projectName = stonecutter.current.project
def loader = projectName.substring(projectName.lastIndexOf('-') + 1)
project.version = mod_version

base {
    archivesName = "${mod_id}-${loader}-${minecraft_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(Integer.parseInt(java_version.toString()))
}

repositories {
    mavenCentral()
    def spongeMaven = maven {
        name = 'Sponge'
        url = 'https://repo.spongepowered.org/repository/maven-public'
    }
    exclusiveContent {
        forRepositories(spongeMaven)
        filter { includeGroupAndSubgroups('org.spongepowered') }
    }
}

processResources {
    var expandProps = ['version'                         : project.version,
                       'group'                           : project.group,
                       'minecraft_version'               : minecraft_version,
                       'minecraft_version_range_fabric'  : minecraft_version_range_fabric,
                       'minecraft_version_range_neoforge': minecraft_version_range_neoforge,
                       'fabric_version'                  : fabric_version,
                       'fabric_loader_version'           : fabric_loader_version,
                       'neoforge_version'                : neoforge_version,
                       'neoforge_loader_version_range'   : neoforge_loader_version_range,
                       'java_version'                    : java_version,
                       'mod_name'                        : mod_name,
                       'mod_authors'                     : mod_authors,
                       'mod_id'                          : mod_id,
                       'mod_icon'                        : mod_icon,
                       'mod_banner'                      : mod_banner,
                       'mod_homepage'                    : mod_homepage,
                       'mod_sources'                     : mod_sources,
                       'mod_issues'                      : mod_issues,
                       'license'                         : license,
                       'description'                     : project.description]

    var jsonExpandProps = expandProps.collectEntries { key, value -> [(key): value instanceof String ? value.replace("\n", "\\\\n") : value]
    }

    filesMatching(['META-INF/mods.toml', 'META-INF/neoforge.mods.toml']) {
        expand expandProps
    }

    filesMatching(['fabric.mod.json']) {
        expand jsonExpandProps
    }

    inputs.properties(expandProps)
}