plugins {
    id 'multiloader-common'
    id 'net.fabricmc.fabric-loom' apply false
    id 'net.fabricmc.fabric-loom-remap' apply false
}

def deobfuscated = stonecutter.eval(minecraft_version, '>=26')
apply plugin: deobfuscated ? 'net.fabricmc.fabric-loom' : 'net.fabricmc.fabric-loom-remap'

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    if (!deobfuscated) mappings loom.officialMojangMappings()
    def modConfig = deobfuscated ? 'implementation' : 'modImplementation'
    add(modConfig, "net.fabricmc:fabric-loader:${fabric_loader_version}")
    add(modConfig, "net.fabricmc.fabric-api:fabric-api:${fabric_version}")
}

loom {
    runs {
        client {
            client()
            setConfigName("Fabric Client (${stonecutter.current.version})")
            ideConfigGenerated(false)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName("Fabric Server (${stonecutter.current.version})")
            ideConfigGenerated(false)
            runDir('runs/server')
        }
    }
}