plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    runs {
        client {
            client()
            ideName = "NeoForge Client (${stonecutter.current.version})"
            gameDirectory = this.mkdir(this.file('runs/client'))
        }
        server {
            server()
            ideName = "NeoForge Server (${stonecutter.current.version})"
            gameDirectory = this.mkdir(this.file('runs/server'))
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}