plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

sourceSets.main.java.srcDirs(rootProject.file('common/src/main/java'), rootProject.file('neoforge/src/main/java'))
sourceSets.main.resources.srcDirs(rootProject.file('common/src/main/resources'), rootProject.file('neoforge/src/main/resources'))

neoForge {
    version = neoforge_version
    runs {
        client {
            client()
            ideName = "NeoForge Client (${stonecutter.current.version})"
            gameDirectory = this.mkdir(this.file('runs/client'))
        }
        server {
            server()
            ideName = "NeoForge Server (${stonecutter.current.version})"
            gameDirectory = this.mkdir(this.file('runs/server'))
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}