# Project
version=1.0.0+1.21.1
group=com.khazoda.windchimes

# Common
minecraft_version=1.21.1
license=Unlicense
mod_name=wind chimes
mod_authors=khazoda, hibi
mod_id=windchimes
mod_icon=windchimes_icon.png
mod_banner=windchimes_banner.png
mod_homepage=https://www.khazoda.com#windchimes
mod_sources=https://github.com/khazoda/windchimes
mod_issues=https://github.com/khazoda/windchimes/issues
description=three wind chimes that sway in the wind and occasionally ring
minecraft_version_range=[1.21,1.21.1]

# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430

# Fabric
fabric_version=0.116.12+1.21.1
fabric_loader_version=0.19.3

# NeoForge
neoforge_version=21.1.234
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
java_version=21
dev.kikugie.stonecutter.hard_mode=true