pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        exclusiveContent {
            forRepository {
                maven {
                    name = 'Fabric'
                    url = uri('https://maven.fabricmc.net')
                }
            }
            filter {
                includeGroupAndSubgroups('net.fabricmc')
            }
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
    id 'dev.kikugie.stonecutter' version '0.9.6'
}

rootProject.name = 'windchimes'

stonecutter {
    centralScript = 'build.gradle'
    kotlinController = false

    shared {
        versions('1.21.1', '26.1')
        vcsVersion = '1.21.1'
    }

    register('common')
    register('fabric')
    register('neoforge')
}