modLoader = "javafml"
loaderVersion = "${neoforge_loader}"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
logoFile = "assets/${id}/banner.png"
logoBlur = false
displayName = "${name}"
displayURL = "${homepage}"
authors = "${authors}"
description = '''${description}'''
issueTrackerURL = "${issues}"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"

[modproperties.${id}]
catalogueImageIcon = "assets/${id}/icon.png"
catalogueBackground = "assets/${id}/background.png"