modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"
issueTrackerURL="${mod_issues}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
logoFile = "assets/${mod_id}/banner.png"
logoBlur = false
displayName = "${mod_name}"
displayURL = "${mod_homepage}"
authors = "${mod_authors}"
description = '''${description}'''

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range_neoforge}"
ordering = "NONE"
side = "BOTH"

[modproperties.${mod_id}]
catalogueImageIcon = "assets/${mod_id}/icon.png"
catalogueBackground = "assets/${mod_id}/background.png"